package com.pip.model;

public enum PIPStatus {
    DRAFT,
    PENDING_HRBP_REVIEW,
    PENDING_EMPLOYEE_ACKNOWLEDGEMENT,
    ACTIVE,
    PENDING_EMPLOYEE_SELF_REVIEW,
    PENDING_MANAGER_REVIEW,
    PENDING_HRBP_DECISION,
    COMPLETED,
    OVERDUE,
    CANCELLED
}
